name: Retrive aws secrets manger

on: 
  push: 
    branches: [main]

jobs:
  get-secrets:
        runs-on: ubuntu-latest
        steps:
          - name: checkout code
            uses: actions/checkout@v3

          - name:  Configure AWS credentials
            uses: aws-actions/configure-aus-credentials@v2
            with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET_KEY }}
                  aws-region: ${{secrets.AWS_REGION }}

          - name: Retrieve secret
            id: get_secret
            run: |
               SECRET-$(aws secretsmanager get-secret-value --secret-id mango/uat/mangouatsecrets --query SecretString --output text)
                echo "Secret: $SECRET"

